# Stage 1
FROM node:12.6.0-alpine as react-build
WORKDIR /app
# Download dependencies
COPY package.json ./package.json
RUN yarn
# Build
COPY . ./
RUN yarn build

# Stage 2 - the production environment
FROM nginx:alpine
COPY --from=react-build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]